
server:
  port : 8761


eureka:
  instance:
    hostname : localhost
  client:
    registerWithEureka : true #是否将自己注册到服务端
    fetchRegistry : false
    serviceUrl:
      #eureka默认空间的地址
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server-1